INSERT INTO hero (ID,english_Name,french_Name) VALUES ('1','Arbiter','Arbitre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('2','Baron','Baron');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('3','Belanor','Belanor');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('4','Blind Seer','Prophetesse Aveugle');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('5','Cruetraxa','Cruetraxa');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('6','Gurgoh the Augur','Gurgoth l''augure');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('7','Hegemon','Hegemon');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('8','Inithwe Bloodtwin','Inithwe Doublesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('9','Ithos','Ithos');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('10','Khoronar','Khoronar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('11','Krisk the Ageless','Krisk l''eternal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('12','Raglin','Raglin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('13','Siphi the Lost Bride','Siphi Mariee Egaree');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('14','Sir Nicholas','Sieur Nicolas');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('15','Soulless','Sans ame');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('16','Tormin the Cold','Tormin le froid');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('17','Turvold','Turvold');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('18','Venus','Venus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('19','Warlord','Seigneur de guerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('20','Wurlim Frostking','Wurlim Roi du gel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('21','Azure','Azur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('22','Baerdal Fellhammer','Beardal Marteaucruel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('23','Basher','Cogneur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('24','Battlesage','Sageguerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('25','Broadmaw','Largegeule');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('26','Cardinal','Cardinale');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('27','Exemplar','Archetype');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('28','Faceless','Sans visage');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('29','Gala Longbraids','Gala Longuenattes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('30','Golden Reaper','Faucheuse Doree');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('31','Lightsworn','Devot de lumiere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('32','Lua','Lua');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('33','Madame Serris','Madame Serris');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('34','Maneater','Mangeur d''homme');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('35','Peydma','Peydma');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('36','Psylar','Psylar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('37','Rowan','Rowan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('38','Seer','Prophetesse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('39','Skullcrown','CouronneCrane');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('40','Skytouched Shaman','Chamane Cieltouche');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('41','Suwai Firstborn','Suwai l''ainee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('42','Towering Titan','Immense Titan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('43','Umbral Enchantress','Sombre enchanteresse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('44','Warcaster','Lance-Guerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('45','Whisper','Murmure');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('46','Amarantine Skeleton','Squelette Pourpre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('47','Arbalester','Arbaletrier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('48','Bellower','Beugleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('49','Bloodhorn','Cornesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('50','Bulwark','Rempart');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('51','Centurion','Centurion');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('52','Chevalier','Chevalier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('53','Coldheart','Coeur-Froid');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('54','Confessor','confesseuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('55','Daywalker','Marcheur de Jour');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('56','Doomscreech','Crisseruine');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('57','Eviscerator','Evisceratrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('58','Fellhound','Chien cruel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('59','Harrier','Harrier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('60','Haruspex','Haruspex');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('61','Harvester','Moissonneuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('62','Hollow','Caverneux');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('63','Huntress','Chasseresse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('64','Ifrit','Ifrit');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('65','Interceptor','Intercepteur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('66','Justiciar','Justicier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('67','Malbranche','Malbranche');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('68','Marquis','Marquis');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('69','Ox','Yak');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('70','Pain Keeper','Garde-Douleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('71','Painsmith','Forgedouleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('72','Paragon','Parangon');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('73','Ragemonger','Pousserage');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('74','Reliquary Tender','Garde-Reliquaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('75','Renegade','Renegate');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('76','Retainer','Domestique');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('77','Seducer','Seducteur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('78','Skirmisher','Escarmoucheuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('79','Steadfast Marshal','Prevôt Inebranlable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('80','Stitched Beast','Bete suturee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('81','Stoneskin','Peaupierre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('82','Vanguard','Avant-garde');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('83','Veteran','Veteran');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('84','Abbess','Abbesse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('85','Bad-el-Kazar','Bad-el-Kazar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('86','Basileus Roanas','Basileus Roanas');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('87','Black Knight','Chevalier Noir');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('88','Bloodgorged','Gorgedesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('89','Brakus the Shifter','Brakus le Metamorphe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('90','Bystophus','Bystophus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('91','Candraphon','Candraphon');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('92','Drexthar Bloodtwin','Drexthar Doublesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('93','Elder Skarg','Skarg l''ancien');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('94','Errol','Errol');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('95','Fu-Shan','Fu-Shan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('96','Minaya','Minaya');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('97','Mountain King','Roi de la Montagne');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('98','Rhazin Scarhide','Rhazin Scarhide');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('99','Robar','Robar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('100','Shirimani','Shirimani');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('101','Skartorsis','Skartosis');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('102','Vizier Ovelis','Vizier Ovelis');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('103','Warchief','Chef de guerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('104','Zavia','Zavia');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('105','Alika','Alika');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('106','Aothar','Aothar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('107','Basilisk','Basilic');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('108','Bloodfeather','Plumesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('109','Bonekeeper','Gardiendos');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('110','Corpse Collector','Ramasse-Cadavres');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('111','Defiled Sinner','Pecheur Souille');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('112','Doompriest','Pretresse de Ruine');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('113','Erinyes','Erinye');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('114','Hexia','Hexia');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('115','Husk','Cosse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('116','Infernal Baroness','Baronne Infernale');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('117','Kallia','Kallia');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('118','Karam','Karam');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('119','Lady Etessa','Dame Etessa');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('120','Lich','Liche');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('121','Luthiea','Luthiea');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('122','Maeve','Maeve');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('123','Mausoleum Mage','Mage de mausolee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('124','Missionary','Missionnaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('125','Nazana','Nazana');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('126','Oathbound','Lie par serment');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('127','Rearguard Sergeant','Arriere-garde');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('128','Reinbeast','Renne Bestial');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('129','Relickeeper','Garde reliquaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('130','Ripper','Eventreur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('131','Romero','Romero');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('132','Seneschal','Senechal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('133','Sepulcher Sentinel','Cerbere Sepulcral');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('134','Shaman','Chamane');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('135','Shatterbones','Brisos');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('136','Sinesha','Sinesha');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('137','Skullcrusher','Ecrasecrane');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('138','Snorting Thug','Brute Bougonne');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('139','Souldrinker','Buveur d''Ame');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('140','Spider','Araignee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('141','Teshada','Teshada');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('142','Thenasil','Thenasil');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('143','Torturehelm','Heaumetorture');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('144','Ursine Icecrusher','Ours Pile-glace');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('145','Ursine Ironhide','Ours Peaudefer');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('146','Yaga the Insatiable','Yaga l''Insatiable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('147','Zargala','Zargala');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('148','Acolyte','Acolyte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('149','Anointed','Oint');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('150','Arcanist','Arcaniste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('151','Beast Wrestler','Dompte-Betes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('152','Bloodpainter','Peintresang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('153','Bogwalker','Sculptemetal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('154','Bombardier','Bombardier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('155','Chaplain','Aumoniere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('156','Courtier','Courtisan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('157','Fencer','Escrimeuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('158','Gladiator','Gladiateur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('159','Goremask','Masquegore');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('160','Grinner','Rictus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('161','Heiress','Heritiere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('162','Honor Guard','Garde d''Honneur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('163','Hurler','Hurleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('164','Ironclad','Cuirasse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('165','Lamellar','Mailles');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('166','Magister','Magister');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('167','Magmablood','Sangmagma');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('168','Mystic Hand','Main Mystique');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('169','Ogryn Jailer','Geolier Ogryn');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('170','Perforator','Perforateur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('171','Preserver','Preservatrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('172','Sentinel','Sentinelle');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('173','Skullsworn','Portecrane');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('174','Slayer','Assassin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('175','Sorceress','Magicienne');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('176','Steel Bowyer','Archere d''Acier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('177','Treefeller','Abatarbre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('178','Twinclaw Disciple','Disciple Deuxgriffes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('179','Warmaiden','Vierge Guerriere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('180','Wretch','Pauvre Here');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('181','Admonitor','Surveillant');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('182','Crusader','Croise');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('183','Cultist','Sectateur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('184','Dead Crusader','Croise Mort');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('185','Duelist','Duelliste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('186','Heartpiercer','Perce-coeur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('187','Hungerer','Affameur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('188','Incubus','Incube');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('189','Intercessor','Intercesseuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('190','Line Infantry','Infanterie de Ligne');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('191','Oldbeard','Vieillebarbe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('192','Outlaw Monk','Moine Hors-la-loi');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('193','Pilgrim','Pelerin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('194','Pit Cur','Batard d''Arene');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('195','Pit Fighter','Guerrier d''Arene');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('196','Redeemer','Redemptrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('197','Sergeant','Sergent');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('198','Skellag','Squelette');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('199','Skullsquire','Cranecuyer');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('200','Spiritwalker','Marchesprit');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('201','Squire','Ecuyer');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('202','Tracker','Traqueur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('203','Vulpine','Vulpin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('204','Axeman','Fendeur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('205','Preacher','Predicatrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('206','Ranger','Ranger');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('207','Sister Militant','Soeur militante');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('208','Altan','Altan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('209','Big ‘Un','Gros Bill');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('210','Cillian the Lucky','Cillian le Chanceux');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('211','Crypt-King Graal','Graal Roi de Crypte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('212','Dracomorph','Dracomorphe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('213','Elenaril','Elenaril');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('214','Foli','Foli');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('215','Grohak the Bloodied','Grohak l''Ensanglanté');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('216','Hakkorhn Smashlord','Hakkorhn Fracapacha');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('217','Ignatius','Ignatius');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('218','Lanakis the Chosen','Lanakis l''Elue');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('219','Longbeard','Longuebarbe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('220','Lord Champfort','Lord Champfort');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('221','Norog','Norog');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('222','Prince Kymar','Prince Kymar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('223','Rae','Rae');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('224','Roshcard the Tower','Roshcard la Tour');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('225','Rotos the Lost Groom','Rotos le Marie Egare');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('226','Scyl of the Drakes','Scyl des Drakes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('227','Sethallia','Sethallia');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('228','Teela Goremane','Teela Toisongore');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('229','Trunda Giltmallet','Trunda Mailletdore');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('230','Tyrant Ixlimor','Tyran Ixlimor');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('231','War Mother','Mere de Guerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('232','Adriel','Adriel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('233','Aina','Aina');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('234','Alure','Charme');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('235','Atur','Atur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('236','Canoness','Chanoinesse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('237','Captain Temila','Capitaine Temila');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('238','Catacomb Councilor','Conseiller Catacombe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('239','Crypt Witch','Sorciere de Crypte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('240','Dark Athel','Sombre Athel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('241','Dark Elhain','Sombre Elhain');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('242','Excruciator','Tortureur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('243','Flesh-Tearer','Dechire-Chair');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('244','Frostbringer','Perceneige');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('245','Gorgorab','Gorgorab');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('246','Grimskin','Peausombre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('247','Grizzled Jarl','Jarl Grisonnant');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('248','Hope','Espoir');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('249','Hordin','Hordin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('250','Jarang','Jarang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('251','Jareg','Jareg');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('252','Jotun','Jotun');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('253','Juliana','Juliana');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('254','Lordly Legionary','Noble Legionnaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('255','Miscreated Monster','Monstre Mal Cree');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('256','Necrohunter','Necrochasseur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('257','Pitiless One','Impitoyable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('258','Royal Guard','Garde Royal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('259','Seeker','Chercheur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('260','Sikara','Sikara');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('261','Tallia','Tallia');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('262','Taurus','Taurus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('263','Tayrel','Tayrel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('264','Ultimate Galek','Galek Supreme');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('265','Adjudicator','Adjudicatrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('266','Apothecary','Apothicaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('267','Athel','Athel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('268','Avenger','Vengeresse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('269','Banshee','Banshee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('270','Cataphract','Cataphractaire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('271','Chopper','Hacheur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('272','Coffin Smasher','ecrase-Cercueil');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('273','Crossbowman','Arbaletrier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('274','Cudgeler','Batonneur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('275','Deathchanter','Chantemort');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('276','Diabolist','Diaboliste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('277','Elder','Ancien');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('278','Elhain','Elhain');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('279','Executioner','Bourreau');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('280','Fleshmonger','Louchebem');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('281','Fortress Goon','Sbire de Forteresse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('282','Frozen Banshee','Banshee Gelee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('283','Galek','Galek');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('284','Gator','Gator');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('285','Grandmaster','Grand-maitre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('286','Gravechill Killer','Tueur Glacesombre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('287','Graybeard','BarbeGrise');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('288','Grumbler','Raleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('289','Hill Nomad','Nomade du Tertre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('290','Hospitaller','Hospitaliere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('291','Hound Spawn','Chien Cruel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('292','Judge','Juge');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('293','Kael','Kael');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('294','Magus','Mage');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('295','Marked','Marquee');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('296','Muckstalker','Pistegadoue');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('297','Myrmidon','Myrmidon');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('298','Pounder','Assomeur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('299','Rocktooth','Dentpierre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('300','Runic Warder','Gardien Runique');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('301','Skink','Scinque');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('302','Slitherbrute','Brutondulante');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('303','Spikehead','Tetepic');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('304','Stout Axeman','Fendeur Robuste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('305','Temptress','Tentatrice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('306','Theurgist','Theurge');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('307','Tormentor','Persecuteur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('308','Valerie','Valerie');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('309','Witness','Temoin');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('310','Archer','Archere');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('311','Aristocrat','Aristocrate');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('312','Battle Sister','Soeur de Combat');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('313','Brute','Brute');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('314','Chemist','Chimiste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('315','Dervish','Derviche');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('316','Frostskin','Peau de givre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('317','Hardscale','Durecaille');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('318','Head Taker','Preneuse de Tete');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('319','Lemure','Lemur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('320','Ritualist','Ritualiste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('321','Sharpshooter','Tireur d''elite');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('322','Skinner','ecorcheur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('323','Sniper','Sniper');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('324','Stalker','Harceleur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('325','Stalwart','Partisan');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('326','Warchanter','Chanteguerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('327','Windtalker','Parlevent');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('328','Word Bearer','Porte-Parole');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('329','Death Hound','Chien du trepas');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('330','Deathknight','Chevalier Mortel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('331','Lurker','Rôdeur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('332','Pikeman','Piquier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('333','Swordsman','epeiste');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('334','Thrall','Vassal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('335','Warboy','Garcon Guerrier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('336','Yeoman','Ribaud');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('337','Astralith','Astralithe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('338','Cupidus','Cupidon');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('339','Duchess Lilitu','Duchesse Lilitu');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('340','Ghostborn','Nespectre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('341','Harvest Jack','Jack le moisonneur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('342','Lord Shazar','Lord Shazar');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('343','Lugan the Steadfast','Lugan l''inebranlable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('344','Lyssandra','Lyssandra');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('345','Ma’Shalled','Ma''Shalled');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('346','Martyr','Martyre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('347','Maulie Tankard','Maulie Chope');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('348','Mortu-Macaab','Mortu-Macaab');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('349','Nethril','Nethril');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('350','Queen Eva','Reine eva');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('351','Richtoff the Bold','Richtoff l''effronte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('352','Royal Huntsman','Chasseur royal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('353','Septimus','Septimus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('354','Shamrock','Trefle');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('355','Suzerain Katonn','Suzerain Katonnn');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('356','Tomb Lord','Seigneur tombeau');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('357','Valkyrie','Valkyrie');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('358','Yannica','Yannica');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('359','Bushi','Bushi');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('360','Cagebreaker','Brisecage');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('361','Crimson Helm','Heaume incarnat');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('362','Deathless','Immortelle');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('363','Delver','Fouilleuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('364','Drake','Drake');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('365','Fang Cleric','Pretre croc');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('366','Fenax','fenax');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('367','Galkut','galkut');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('368','Hellgazer','mirenfer');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('369','High Khatun','haute khatun');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('370','Jinglehunter','chasse-grelot');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('371','Jizoh','jizoh');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('372','Knight-Errant','chevalier errant');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('373','Kytis','kytis');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('374','Luria','luria');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('375','Marksman','Archer d''elite');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('376','Mistress of Hymns','maitresse des hymnes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('377','Occult Brawler','castagneur occulte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('378','Rock Breaker','brise-pierre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('379','Sandlashed Survivor','survivant au sable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('380','Stag Knight','chevalier cerf');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('381','Steelskull','cranedacier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('382','Terrorbeast','beteffroyable');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('383','Valla','valla');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('384','Vergis','vergis');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('385','Vrask','vrask');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('386','Warden','gardien');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('387','Woad-Painted','guede-peinte');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('388','Zelotah','zelotah');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('389','Berserker','berseker');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('390','Bloodbraid','nattesang');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('391','Bone Knight','chevalier d''os');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('392','Channeler','Medium');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('393','Conquerer','conquerant');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('394','Corpulent Cadaver','cadavre corpulent');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('395','Crimson Slayer','tueuse incarnate');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('396','Flesheater','mangechair');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('397','Flinger','Lanceur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('398','Furystoker','soutierfurieux');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('399','Ghoulish Ranger','ranger macabre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('400','Gnarlhorn','cornenoueuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('401','Grappler','bagarreur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('402','Guardian','Gardien');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('403','Halberdier','Hallebardier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('404','Hatchet Slinger','Lance-hachettes');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('405','Hellfang','croc infernal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('406','Hexweaver','tissesortilege');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('407','Hyria','Hyrie');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('408','Judicator','Magistrat');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('409','Madman','desaxe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('410','Maiden','jouvencelle');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('411','Marquess','marquise');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('412','Master Butcher','maitre boucher');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('413','Metalshaper','sculptemetal');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('414','Mother Superior','mere superieure');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('415','Penitent','penitente');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('416','Raider','pillarde');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('417','Rotting Mage','mage pourissant');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('418','Siegebreaker','brisesiege');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('419','Slasher','balafreur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('420','Soulbond Bowyer','archer chainame');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('421','Spirithost','hôtesprit');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('422','Templar','templier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('423','Totem','totem');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('424','Wanderer','vagabond');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('425','Warpriest','pretresse de guerre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('426','Armiger','armorie');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('427','Commander','commandeur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('428','Crusher','broyeuse');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('429','Dhampir','dhampire');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('430','Elfguard','gardelfe');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('431','Fireblade','lamardente');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('432','Frontline Warrior','Guerrier de Front');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('433','Herald','Heraut');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('434','Jaeger','Jaeger');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('435','Militia','Milice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('436','Outlander','etranger');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('437','Outrider','Guide');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('438','Pitspawn','Frai de Mine');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('439','Satyr','Satyre');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('440','Saurus','Saurus');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('441','Shieldguard','Gardebouclier');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('442','Slicer','Trancheur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('443','Thrasher','Bastonneur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('444','Throatcutter','Coupegorge');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('445','Tunnel Steward','Intendant de Tunnel');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('446','Vigilante','Vigile');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('447','Vilespawn','Vil Rejeton');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('448','Zephyr Sniper','Sniper Zephyr');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('449','Bandit','Bandit');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('450','Bully','Despote');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('451','Hellhound','Chien de l''enfer');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('452','Knecht','Serviteur');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('453','Magekiller','Tueuse de Mage');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('454','Novitiate','Novice');
INSERT INTO hero (ID,english_Name,french_Name) VALUES ('455','Troglodyte','Troglodyte');
