INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('1','Abbess','Abbesse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-abbesse-abbess-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('2','Acolyte','Acolyte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-acolyte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('3','Adjudicator','Adjudicatrice','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-adjudicatrice-adjudicator-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('4','Admonitor','Surveillant','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('5','Adriel','Adriel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-adriel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('6','Aina','Aina','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-aina-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('7','Alika','Alika','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-alika-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('8','Altan','Altan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-altan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('9','Alure','Charme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-charme-alure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('10','Amaratine Skeleton','Squelette pourpre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-squelette-pourpre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('11','Angar','Angar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-angar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('12','Anointed','Oint','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-oint-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('13','Aothar','Aothar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aothar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('14','Apothecary','Apothicaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-apothicaire-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('15','Arbalester','Arbaletrier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-arbaletrier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('16','Arbiter','Arbitre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arbitre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('17','Arcanist','Arcaniste','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-arcaniste-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('18','Archer','Archer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('19','Aristocrat','Aristocrate','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('20','Armiger','Armorie','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('21','Astralith','Astralithe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-astralithe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('22','Athel','Athel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-athel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('23','Atur','Atur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-atur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('24','Avenger','Vengeresse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vengeresse-avenger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('25','Axeman','Fendeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('26','Azure','Azur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-azur-azure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('27','Bad-el-Kazar','Bad-el-Kazar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bad-el-kazar-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('28','Baerdal Fellhammer','Baerdal Marteaucruel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-baerdal-marteaucruel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('29','Bandit','Bandit','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('30','Banshee','Banshee','alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-banshee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('31','Baron','Baron','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-baron-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('32','Basher','Cogneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cogneur-basher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('33','Basileus Roanas','Basileus Roanas','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-basileus-roanas-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('34','Basilisk','Basilic','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-basilic-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('35','Battle Sister','Soeur de Combat','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('36','Battlesage','Sageguerre ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sageguerre-battlesage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('37','Beast Wrestler','Dompte-Betes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-dompte-betes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('38','Belanor','Belanor','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-belanor-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('39','Bellower','Beugleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-beugleur-bellower-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('40','Berserker','Berserker','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-berserker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('41','Big Un','Gros Bill','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gros-bill-big-un-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('42','Black Knight','Chevalier Noir','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-noir-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('43','Blind Seer','Prophetesse Aveugle','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prophetesse-aveugle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('44','Bloodbraid','Nattesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-nattesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('45','Bloodfeather','Plumesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-plumesang-bloodfeather-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('46','Bloodgorged','Gorgedesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gorgedesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('47','Bloodhorn','Cornesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cornesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('48','Bloodpainter','Peintresang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-peintresang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('49','Bogwalker','Marchemarais','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marchemarais-bogwalker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('50','Bombardier','Bombardier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-bombardier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('51','Bone Knight','Chevalier d’Os ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chevalier-dos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('52','Bonekeeper','Gardiendos','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gardiendos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('53','Brakus The Shifter','Brakus le Metamorphe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brakus-le-metamorphe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('54','Broadmaw','Largegueule','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-largegueule-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('55','Brute','Brute','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('56','Bully','Brute','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('57','Bulwark','Rempart','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rempart-bulwark-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('58','Bushi','Bushi','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-bushi-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('59','Bystophus','Bystophus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bystophus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('60','Cagebreaker','Brisecage','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brisecage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('61','Candraphon','Candraphon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-candraphon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('62','Canoness','Chanoinesse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chanoinesse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('63','Captain Temila','Capitaine Temila','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-capitaine-temila-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('64','Cardinal','Cardinale','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cardinale-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('65','Catacomb Councilor','Conseiller Catacombe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-conseiller-catacombe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('66','Cataphract','Cataphractaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cataphractaire-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('67','Centurion','Centurion','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-centurion-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('68','Channeler','Medium','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-medium-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('69','Chaplain','Aumôniere','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-aumoniere-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('70','Chemist','Chimiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('71','Chevalier','Chevalier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chevalier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('72','Chopper','Hacheur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hacheur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('73','Cillian the Lucky','Cillian le Chanceux','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cillian-le-chanceux-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('74','Coffin Smasher','ecrase-Cercueil','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ecrase-cercueil-coffin-smasher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('75','Coldheart','CoeurFroid','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-coeurfroid-coldheart-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('76','Commander','Commandeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('77','Confessor','Confesseuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-confesseuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('78','Conquerer','Conquerant','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-conquerant-conquerer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('79','Corpse Collector','Ramasse-Cadavres','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ramasse-cadavres-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('80','Corpulent Cadaver','Cadavre Corpulent','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cadavre-corpulent-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('81','Courtier','Courtisan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-courtisan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('82','Crimson Helm','Heaume incarnat','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-heaume-incarnat-rimson-helm-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('83','Crimson Slayer','Tueuse Incarnate','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tueuse-incarnate-crimson-slayer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('84','Crossbowman','Arbaletrier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-arbaletrier-crossbowman-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('85','Cruetraxa','Cruetraxa','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cruetraxa-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('86','Crusader','Croise ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('87','Crusher','Broyeuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('88','Crypt-King Graal','Graal Roi de Crypte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-graal-roi-de-crypte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('89','Crypt-Witch','Sorciere de Crypte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sorciere-de-crypte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('90','Cudgeler','Bâtonneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-batonneur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('91','Cultist','Sectateur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('92','Cupidus','Cupidon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cupidon-cupidus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('93','Dark Athel','Sombre Athel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-athel-dark-athel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('94','Dark Elhain','Sombre Elhain','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-elhain-dark-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('95','Daywalker','Marcheur de jour','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marcheur-de-jour-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('96','Dead Crusader','Croise Mort','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('97','Death Hound','Chien du Trepas','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('98','Deathchanter','Chantemort','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chantemort-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('99','Deathknight','Chevalier Mortel','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('100','Deathless','Immortelle','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-immortelle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('101','Defiled Sinner','Pecheur Souille','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-pecheur-souille-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('102','Delver','Fouilleuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fouilleuse-delver-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('103','Dervish','Derviche ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('104','Dhampire','Dhampire','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('105','Diabolist','Diaboliste','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-diaboliste-diabolist-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('106','Doompriest','Pretresse de ruine','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pretresse-de-ruine-doompriest-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('107','Doomscreech','Crisseruine','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-crisseruine-doomscreech-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('108','Dracomorph','Dracomorphe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dracomorphe-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('109','Drake','Drake','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drake-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('110','Drexthar Bloodtwin','Drexthar Doublesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drexthar-doublesang-drexthar-bloodtwin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('111','Duchess Lilitu','Duchesse Lilitu','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-duchesse-lilitu-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('112','Duelist','Duelliste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('113','Elder','Ancien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-ancien-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('114','Elder Skarg','Skarg l Ancien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-skarg-lancien-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('115','Elenaril','Elenaril','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-elenaril-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('116','Elfguard','Gardelfe','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('117','Elhain','Elhain','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elhain-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('118','Erinyes','Erinye','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-erinye-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('119','Errol','Errol','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-errol-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('120','Eviscerator','Evisceratrice','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-evisceratrice-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('121','Excruciator','Tortureur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tortureur-excruciator-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('122','Executioner','Bourreau','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bourreau-executioner-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('123','Exemplar','Archetype','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-archetype-exemplar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('124','Faceless','Sans visage','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sans-visage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('125','Fang Cleric','Pretre Croc','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-pretre-croc-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('126','Fellhound','Chien Cruel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chien-cruel-fellhound-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('127','Fenax','Fenax','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-fenax-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('128','Fencer','Escrimeuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-escrimeuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('129','Fireblade','Lamardente ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('130','Flesh Tearer','Dechire-Chair','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-dechire-chair-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('131','Flesheater','Mangechair','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mangechair-flesheater-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('132','Fleshmonger','Louchebem','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-louchebem-fleshmonger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('133','Flinger','Lanceur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lanceur-flinger-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('134','Foli','Foli','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-foli-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('135','Fortress Goon','Sbire de Forteresse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sbire-de-forteresse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('136','Frontline Warrior','Guerrier de Front','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('137','Frostbringer','Perceneige','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-perceneige-frostbringer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('138','Frostskin','Peau de givre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('139','Frozen Banshee','Banshee Gelee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-banshee-gelee-frozen-banshee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('140','Furystroker','SoutierFurieux','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-soutierfurieux-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('141','Fu-Shan','Fu-Shan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fu-shan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('142','Gala Longbraids','Gala Longuenattes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gala-longuenattes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('143','Galek','Galek','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galek-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('144','Galkut','Galkut','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galkut-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('145','Gator','Gator','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gator-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('146','Ghostborn','Nespectre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-nespectre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('147','Ghoulish Ranger','Ranger Macabre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-ranger-macabre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('148','Gladiator','Gladiateur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gladiateur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('149','Gnarlhorn','Cornenoueuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cornenoueuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('150','Golden Reaper','Faucheuse Doree','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-faucheuse-doree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('151','Goremask','Masquegore','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-masquegore-goremask-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('152','Gorgorab','Gorgorab','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gorgorab-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('153','Grandmaster','Grand-maitre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-grand-maitre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('154','Grappler','Bagarreur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-bagarreur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('155','Gravechill Killer','Tueur Glacetombe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tueur-glacetombe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('156','Graybeard','Barbegrise','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-barbegrise-graybeard-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('157','Grimskin','Peausombre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-peausombre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('158','Grinner','Rictus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rictus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('159','Grizzled Jarl','Jarl Grisonnant','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jarl-grisonnant-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('160','Grohak The Bloodied','Grohak l Ensanglante','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-grohak-lensanglante-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('161','Grumbler','Râleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-raleur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('162','Guardian','Gardien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gardien-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('163','Gurgoh Augur','Gurgoth l Augure','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gurgoth-laugure-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('164','Gurptuk Moss-Beard','Gurptuk Barbe-Mousse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gurptuk-barbe-mousse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('165','Hakkorhn Smashlord','Hakkorhn Fracapacha','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hakkorhn-fracapacha-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('166','Halberdier','Hallebardier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hallebardier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('167','Hardscale','Durecaille','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('168','Harrier','Harrier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-harrier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('169','Haruspex','Haruspex','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-haruspex-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('170','Harvest Jack','Jack le Moissonneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jack-le-moissonneur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('171','Harvester','Moissonneuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-moissonneuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('172','Hatchet Slinger','Lance-hachettes ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lance-hachettes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('173','Head Taker','Preneuse de Tete','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('174','Heartpiercer','Perce-coeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('175','Hegemon','Hegemon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hegemon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('176','Heiress','Heritiere','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-heritiere-heiress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('177','Hellfang','Croc infernal ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-croc-infernal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('178','Hellgazer','Mirenfer','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mirenfer-hellgazer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('179','Hellhound','Chien de l enfer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('180','Herald','Heraut','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('181','Hexia','Hexia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hexia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('182','Hexweaver','Tissesortilege','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tissesortilege-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('183','High Khatun','Haute Khatun','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-haute-khatun-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('184','Hill Nomad','Nomade du Tertre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-nomade-du-tertre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('185','Hollow','Caverneux','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-caverneux-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('186','Honor Guard','Garde d Honneur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-garde-dhonneur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('187','Hope','Espoir','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-espoir-hope-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('188','Hordin','Hordin','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hordin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('189','Hospitaller','Hospitaliere','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hospitaliere-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('190','Houndspawn','Rejeton de Cabot','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rejeton-de-cabot-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('191','Hungerer','Affameur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('192','Huntress','Chasseresse ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chasseresse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('193','Hurler','Hurleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hurleur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('194','Husk','Cosse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cosse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('195','Hyria','Hyrie','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-hyrie-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('196','Ifrit','Ifrit','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-ifrit-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('197','Ignatius','Ignatius','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ignatius-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('198','Incubus','Incube','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('199','Infernal Baroness','Baronne Infernale','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-baronne-infernale-infernal-baroness-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('200','Inithwe Bloodtwin','Inithwe Doublesang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-inithwe-doublesang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('201','Interceptor','Intercepteur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-intercepteur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('202','Intercessor','Intercesseuse','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('203','Ironclad','Cuirasse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-cuirasse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('204','Ithos','Ithos','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ithos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('205','Jaeger','Jaeger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('206','Jarang','Jarang','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jarang-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('207','Jareg','Jareg','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jareg-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('208','Jinglehunter','Chasse-Grelot','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chasse-grelot-jinglehunter-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('209','Jizoh','Jizoh','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jizoh-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('210','Jotun','Jotun','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jotun-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('211','Judge','Juge','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-juge-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('212','Judicator','Magistrat','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-magistrat-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('213','Juliana','Juliana','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-juliana-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('214','Justiciar','Justicier ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-justicier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('215','Kael','Kael','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kael-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('216','Kallia','Kallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('217','Karam','Karam','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-karam-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('218','Khoronar','Khoronar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-khoronar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('219','Knecht','Serviteur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('220','Knight Errant','Chevalier Errant','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chevalier-errant-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('221','Krisk The Ageless','Krisk L Eternel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krisk-leternel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('222','Kytis','Kytis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-kytis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('223','Lady Etessa','Dame Etessa','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-dame-etessa-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('224','Lamellar','Mailles','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-mailles-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('225','Lanakis The Chosen','Lanakis l elue','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lanakis-lelue-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('226','Lemure','Lemur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('227','Lich','Liche','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-liche-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('228','Lightsworn','Devot de Lumiere','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-devot-de-lumiere-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('229','Line Infantry','Infanterie de Ligne','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('230','Longbeard','Longuebarbe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-longuebarbe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('231','Lord Champfort','Lord champfort','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lord-champfort-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('232','Lord Shazar','Lord Shazar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lord-shazar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('233','Lordly Legionary','Noble Legionnaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-noble-legionnaire-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('234','Lua','Lua','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lua-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('235','Lugan the Steadfast','Lugan l Inebranlable ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lugan-linebranlable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('236','Luria','Luria','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-luria-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('237','Lurker','Rôdeur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('238','Lutheia','Luthiea','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-luthiea-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('239','Lyssandra','Lyssandra','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lyssandra-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('240','Ma Shalled','Ma Shalled','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mashalled-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('241','Madame Serris','Madame Serris','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-madame-serris-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('242','Madman','Desaxe','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-desaxe-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('243','Maeve','Maeve','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maeve-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('244','Mage killeur','Tueuse de Mage','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('245','Magister','Magister','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-magister-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('246','Magmablood','Sangmagma','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sangmagma-magmablood-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('247','Magus','Mage','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mage-magus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('248','Maiden','Jouvencelle','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-jouvencelle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('249','Malbranche','Malbranche','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-malbranche-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('250','Maneater','Mangeur d Homme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mangeur-dhomme-maneater-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('251','Marked','Marquee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marquee-marked-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('252','Marksman','Archer d elite','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-archer-delite-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('253','Marquess','Marquise','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marquise-marquess-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('254','Marquis','Marquis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-marquis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('255','Martyr','Martyre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-martyre-martyr-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('256','Master Butcher','Maître Boucher','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-maitre-boucher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('257','Maulie Tankard','Maulie Chope','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-maulie-chope-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('258','Mausoleum Mage','Mage de Mausolee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mage-de-mausolee-mausoleum-mage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('259','Metalshaper','Sculptemetal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sculptemetal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('260','Militia','Milice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('261','Minaya','Minaya','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-minaya-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('262','Miscreated Monster','Monstre Mal Cree','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-monstre-mal-cree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('263','Missionary','Missionnaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-missionnaire-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('264','Mistress of Hymns','Maîtresse des Hymnes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maitresse-des-hymnes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('265','Mortu-Macaab','Mortu-Macaab','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mortu-macaab-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('266','Mother Superior','Mere Superieur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-mere-superieur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('267','Mountain King','Roi de la montagne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-roi-de-la-montagne-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('268','Muckstalker','Pistegadoue','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pistegadoue-muckstalker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('269','Myrmidon','Myrmidon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-myrmidon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('270','Mystic Hand','Main Mystique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-main-mystique-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('271','Nazana','Nazana','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nazana-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('272','Necrohunter','Necrochasseur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-necrochasseur-necrohunter-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('273','Nethril','Nethril','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nethril-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('274','Norog','Norog','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-norog-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('275','Novitiate','Novice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('276','Oathbound','Lie par serment','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lie-par-serment-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('277','Occult Brawler','Castagneur Occulte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-castagneur-occulte-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('278','Ogryn Jailer','Geôlier Ogryn','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-geolier-ogryn-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('279','Oldbeard','Vieillebarbe','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('280','Outlander','Etranger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('281','Outlaw Monk','Moine Hors-la-loi ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-moine-hors-la-loi-monk-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('282','Outrider','Guide ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('283','Ox','Yak','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-yak-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('284','Pain keeper','Garde-Douleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-douleur-pain-keeper-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('285','Painsmith','Forgedouleur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-forgedouleur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('286','Paragon','Parangon','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-parangon-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('287','Penitent','Penitente','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-penitente-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('288','Perforator','Perforateur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-perforateur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('289','Peydma','Peydma','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-peydma-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('290','Pikeman','Piquier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('291','Pilgrim','Pelerin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('292','Pit Cur','Batard d Arene','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('293','Pit Fighter','Guerrier d Arene','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('294','Pitiless One','Impitoyable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-impitoyable-pitiless-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('295','Pitspawn','Frai de Mine ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('296','Pounder','Assommeur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-assommeur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('297','Preacher','Predicatrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('298','Preserver','Preservatrice','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-preservatrice-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('299','Prince Kymar','Prince Kymar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prince-kymar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('300','Psylar','Psylar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-psylar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('301','Queen Eva','Reine eva','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-reine-eva-queen-eva-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('302','Rae','Rae','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rae-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('303','Ragemonger','Pousserage','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-pousserage-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('304','Raglin','Raglin','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-raglin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('305','Raider','Pillarde','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-pillarde-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('306','Ranger','Ranger','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('307','Rearguard Sergeant','Arriere-garde','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arriere-garde-rearguard-sergeant-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('308','Redeemer','Redemptrice','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('309','Reinbeast','Renne Bestial','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-renne-bestial-reinbeast-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('310','Relickeeper','Garderelique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garderelique-relickeeper-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('311','Reliquary Tender','Garde-Reliquaire','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-reliquaire-reliquary-tender-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('312','Renegade','Renegate','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-renegate-renegade-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('313','Retainer','Domestique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-domestique-retainer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('314','Rhazin Scarhide','Rhazin Peaumarquee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rhazin-peaumarquee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('315','Richtoff The Bold','Richtoff l’Effronte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-richtoff-leffronte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('316','Ripper','Eventreur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-eventreur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('317','Ritualist','Ritualiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('318','Robar','Robar','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-robar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('319','Rock Breaker','Brise-pierre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brise-pierre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('320','Rocktooth','Dentpierre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dentpierre-rocktooth-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('321','Romero','Romero','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-romero-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('322','Roshcard The Tower','Roshcard la Tour','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roshcard-la-tour-roshcard-the-tower-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('323','Rotos The Lost Groom','Rotos le Marie Egare','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-rotos-le-marie-egare-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('324','Rotting Mage','Mage Pourrissant','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-mage-pourrissant-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('325','Rowan','Rowan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rowan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('326','Royal Guard','Garde Royal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-royal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('327','Royal Huntsman','Chasseur Royal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chasseur-royal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('328','Runic Warder','Gardien Runique','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-gardien-runique-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('329','Sandlashed Survivor','Survivante au Sable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-survivante-au-sable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('330','Satyr','Satyre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('331','Saurus','Saurus','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('332','Scyl of the Drakes','Scyl des Drakes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-scyl-des-drakes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('333','Seducer','Seducteur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seducteur-seducer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('334','Seeker','Chercheur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chercheur-seeker-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('335','Seer','Prophetesse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-prophetesse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('336','Seneschal','Senechal','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-senechal-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('337','Sentinel','Sentinelle','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sentinelle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('338','Septimus','Septimus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-septimus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('339','Sepulcher Sentinel','Cerbere Sepulcral','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cerbere-sepulcral-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('340','Sergeant','Sergent ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('341','Sethallia','Sethallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sethallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('342','Shaman','Chamane','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chamane-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('343','Shamrock','Shamrock','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-trefle-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('344','Sharpshooter','Tireur d elite','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('345','Shatterbones','Brisos','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brisos-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('346','Shieldguard','Gardebouclier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('347','Shirimani','Shirimani','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-shirimani-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('348','Siegebreaker','Brisesiege','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brisesiege-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('349','Sikara','Sikara','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sikara-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('350','Sinesha','Sinesha','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sinesha-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('351','Siphi The Lost Bride','Siphi Mariee Egaree','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-siphi-mariee-egaree-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('352','Sir Nicholas','Sieur Nicolas','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sieur-nicolas-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('353','Sister Militant','Sœur Militante','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('354','Skartorsis','Skartorsis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-skartorsis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('355','Skellag','Squelette ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('356','Skink','Scinque','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-scinque-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('357','Skinner','Ecorcheur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('358','Skirmisher','Escarmoucheuse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-escarmoucheuse-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('359','Skull Lord Var-Gall','Lord Crâne Var-Gall','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lord-crane-var-gall-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('360','Skullcrown','CouronneCrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-couronnecrane-skullcrown-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('361','Skullcrusher','ecraseCrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ecrasecrane-skullcrusher-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('362','Skullsquire','Cranecuyer ','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('363','Skullsworn','Portecrâne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-portecrane-skullsworn-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('364','Skytouched Shaman','Chamane Cieltouche','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chamane-cieltouche-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('365','Slasher','Balafreur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-balafreur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('366','Slayer','Assassin','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-assassin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('367','Slicer','Trancheur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('368','Slitherbrute','Brutondulante','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brutondulante-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('369','Sniper','Sniper','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sniper-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('370','Snorting Thug','Brute Bougonne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-brute-bougonne-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('371','Sorceress','Magicienne','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-magicienne-sorceress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('372','Soulbond Bowyer','Archer Chaînâme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-archer-chainame-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('373','Souldrinker','Buveur d’âme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-buveur-dame-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('374','Souless','Sans Ame','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-sans-ame-soulless-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('375','Spider','Araignee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-araignee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('376','Spikehead','Tetepic','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tetepic-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('377','Spirithost','Hôtesprit','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hotesprit-spirithost-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('378','Spiritwalker','Marchesprit','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('379','Squire','Ecuyer','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('380','Stag Knight','Chevalier Cerf','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-cerf-stag-knigh-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('381','Stalker','Harceleur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('382','Stalwart','Partisan','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('383','Steadfast Marshall','Prevôt inebranlable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-prevot-inebranlable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('384','Steel Bowyer','Archere d Acier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-archere-dacier-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('385','Steelskull','Crânedacier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cranedacier-steelskull-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('386','Stitched Beast','Bete suturee ','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-bete-suturee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('387','Stoneskin','Peaupierre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-peaupierre-stoneskin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('388','Stout Axeman','Fendeur Robuste','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-fendeur-robuste-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('389','Suwai Firstborn','Suwai l Aînee','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-suwai-lainee-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('390','Suzerain Katonn','Suzerain Katonn','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-suzerain-katonn-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('391','Swordsman','epeiste','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('392','Tallia','Tallia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tallia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('393','Taurus','Taurus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-taurus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('394','Tayrel','Tayrel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tayrel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('395','Teela Goremane','Teela Toisongore','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-teela-toisongore-teela-goremane-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('396','Templar','Templier','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-templier-templar-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('397','Temptress','Tentatrice','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tentatrice-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('398','Terrorbeast','Beteffroyable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-beteffroyable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('399','Teshada','Teshada','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-teshada-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('400','Thenasil','Thenasil','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-thenasil-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('401','Theurgist','Theurge','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-theurge-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('402','Thrall','Vassal','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('403','Thrasher','Bastonneur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('404','Throatcutter','Coupegorge','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('405','Tomb Lord','Seigneur Tombeau','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-seigneur-tombeau-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('406','Tormentor','Persecuteur','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-persecuteur-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('407','Tormin the Cold','Tormin le Froid','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tormin-le-froid-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('408','Torturehelm','Heaumetorture','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-heaumetorture-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('409','Totem','Totem','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-totem-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('410','Towering Titan','Immense Titan','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-immense-titan-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('411','Tracker','Traqueur','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('412','Treefeller','Abatarbre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-abatarbre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('413','Troglodyte','Troglodyte','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('414','Trunda Giltmallet','Trunda MailletDore','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-trunda-mailletdore-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('415','Tunnel Steward','Intendant de Tunnel','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('416','Turvold','Turvold','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-turvold-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('417','Twinclaw Disciple','Disciple Deuxgriffes','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-disciple-deuxgriffes-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('418','Tyrant Ixlimor','Tyrant Ixlimor','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-tyran-ixlimor-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('419','Ultimate Galek','Galek Supreme','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galek-supreme-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('420','Umbral Enchantress','Sombre Enchanteresse','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sombre-enchanteresse-umbreal-enchantress-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('421','Ursine Icecrusher','Ours Pile-Glace','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-ours-pile-glace-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('422','Ursine Ironhide','Ours Peaudefer','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ours-peaudefer-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('423','Valerie','Valerie','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valerie-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('424','Valkyrie','Valkyrie','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valkyrie-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('425','Valla','Valla','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valla-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('426','Vanguard','Avant-garde','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-avant-garde-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('427','Venus','Venus','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-venus-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('428','Vergis','Vergis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-vergis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('429','Veteran','Veteran','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-veteran-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('430','Vigilante','Vigile','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('431','Vilespawn','Vil Rejeton','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('432','Vizier Ovelis','Vizier Ovelis','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-vizir-ovelis-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('433','Vrask','Vrask','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vrask-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('434','Vulpine','Vulpin','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('435','Wanderer','Vagabond','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-vagabond-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('436','War Mother','Mere de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-mere-de-guerre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('437','Warboy','Garçon guerrier','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('438','Warcaster','Lance-guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-lance-guerre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('439','Warchanter','Chanteguerre','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('440','Warchief','Chefdeguerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-chefdeguerre-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('441','Warden','Gardien','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gardien-warden-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('442','Warlord','Seigneur de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seigneur-de-guerre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('443','Warmaiden','Vierge guerriere','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vierge-guerriere-warmaiden-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('444','Warpriest','Pretresse de Guerre','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pretresse-de-guerre-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('445','Whisper','Murmure','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-murmure-equipement-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('446','Windtalker','Parlevent','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('447','Witness','Temoin','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-temoin-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('448','Woad Painted','Guede-Peinte','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-guede-peinte-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('449','Word Bearer','Porte-Parole','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('450','Wretch','Pauvre Here','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-pauvre-here-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('451','Wurlim Frostking','Wurlim Roi du Gel','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-wurlim-roi-du-gel-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('452','Yaga the Insatiable','Yaga l insatiable','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yaga-linsatiable-yaga-the-insatiable-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('453','Yannica','Yannica','https://www.alucare.fr/wiki/guide-raid-shadow-legend/champion/guide-sur-yannica-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('454','Yeoman','Ribaud','AIE AIE AIE, pas encore de guide !');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('455','Zargala','Zargala','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zargala-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('456','Zavia','Zavia','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zavia-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('457','Zelotah','Zelotah','https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zelotah-artefact-et-maitrise/');
INSERT INTO hero (ID,english_Name,french_Name, url) VALUES ('458','Zephyr Sniper','Sniper Zephyr ','AIE AIE AIE, pas encore de guide !');